name: UPB Desplegando a un EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 #plugin para clonar el repositorio

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7 #plugin para copiar archivos via SCP
        with:
          host: ${{ secrets.EC2_HOST }} #direccion IP de la instancia EC2
          username: ${{ secrets.EC2_USER }}  #usuario para acceder a la instancia EC2
          key: ${{ secrets.EC2_KEY }} #llave privada para acceder a la instancia EC2
          source: "index.html"
          target: "/var/www/html"